-- =========================================================
-- Base de datos temporal para pruebas automatizadas en CI
-- Proyecto: Line White Services
-- =========================================================

DROP FUNCTION IF EXISTS FN_CONSULTA_LOGIN(VARCHAR);
DROP FUNCTION IF EXISTS FN_CONSULTA_LOGIN_SESION(INTEGER);
DROP TABLE IF EXISTS USUARIOS CASCADE;

-- =========================================================
-- Tabla mínima requerida por Passport
-- =========================================================

CREATE TABLE USUARIOS (
    ID_USUARIO INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    CEDULA VARCHAR(25)
        NOT NULL
        UNIQUE,

    NOMBRES VARCHAR(100)
        NOT NULL,

    APELLIDOS VARCHAR(100)
        NOT NULL,

    ID_TIPO_USUARIO INTEGER
        NOT NULL,

    PASSWORD_HASH VARCHAR(255)
        NOT NULL
);

-- =========================================================
-- Usuario exclusivo para GitHub Actions
--
-- Usuario: 8-999-9999
-- Password: Qa_pipeline_2026#
-- Tipo permitido: 0
-- =========================================================

INSERT INTO USUARIOS (
    ID_USUARIO,
    CEDULA,
    NOMBRES,
    APELLIDOS,
    ID_TIPO_USUARIO,
    PASSWORD_HASH
)
VALUES (
    1,
    '8-999-9999',
    'Usuario',
    'Pipeline QA',
    0,
    '$argon2id$v=19$m=65536,p=4,t=3$tGCr0GYy+47ikXGvxFzCiA$rxCMRu0G+F/3oWB4uVt/K1+du0fMTuW39qbGXbUrhHk'
);

-- =========================================================
-- Consulta utilizada durante el login
-- =========================================================

CREATE OR REPLACE FUNCTION FN_CONSULTA_LOGIN(
    REQ_CEDULA VARCHAR(25)
)
RETURNS TABLE(
    ID INTEGER,
    CEDULA VARCHAR(25),
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    ID_TIPO_USUARIO INTEGER,
    PASSWORD_HASH VARCHAR(255),
    RES_RESPUESTA VARCHAR(2),
    RES_RESPUESTA_MSG VARCHAR(150)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        U.ID_USUARIO,
        U.CEDULA,
        U.NOMBRES,
        U.APELLIDOS,
        U.ID_TIPO_USUARIO,
        U.PASSWORD_HASH,
        'SI'::VARCHAR(2),
        'USUARIO AUTORIZADO'::VARCHAR(150)
    FROM USUARIOS U
    WHERE U.CEDULA = REQ_CEDULA;

    IF NOT FOUND THEN
        RETURN QUERY
        SELECT
            NULL::INTEGER,
            REQ_CEDULA,
            NULL::VARCHAR(100),
            NULL::VARCHAR(100),
            NULL::INTEGER,
            NULL::VARCHAR(255),
            'NO'::VARCHAR(2),
            'USUARIO NO EXISTE'::VARCHAR(150);
    END IF;
END;
$$;

-- =========================================================
-- Consulta utilizada por deserializeUser
-- =========================================================

CREATE OR REPLACE FUNCTION FN_CONSULTA_LOGIN_SESION(
    ID_USER INTEGER
)
RETURNS TABLE(
    ID INTEGER,
    CEDULA VARCHAR(25),
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    ID_TIPO_USUARIO INTEGER,
    RES_RESPUESTA VARCHAR(2),
    RES_RESPUESTA_MSG VARCHAR(150)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        U.ID_USUARIO,
        U.CEDULA,
        U.NOMBRES,
        U.APELLIDOS,
        U.ID_TIPO_USUARIO,
        'SI'::VARCHAR(2),
        'USUARIO AUTORIZADO'::VARCHAR(150)
    FROM USUARIOS U
    WHERE U.ID_USUARIO = ID_USER;

    IF NOT FOUND THEN
        RETURN QUERY
        SELECT
            NULL::INTEGER,
            NULL::VARCHAR(25),
            NULL::VARCHAR(100),
            NULL::VARCHAR(100),
            NULL::INTEGER,
            'NO'::VARCHAR(2),
            'USUARIO NO EXISTE'::VARCHAR(150);
    END IF;
END;
$$;

-- =========================================================
-- Verificación visible en los logs del pipeline
-- =========================================================

SELECT
    ID_USUARIO,
    CEDULA,
    NOMBRES,
    APELLIDOS,
    ID_TIPO_USUARIO
FROM USUARIOS;